# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'szablon_scr.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(687, 549)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.chart = QtWidgets.QVBoxLayout()
        self.chart.setObjectName("chart")
        self.gridLayout.addLayout(self.chart, 0, 0, 1, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.chart1 = QtWidgets.QHBoxLayout()
        self.chart1.setObjectName("chart1")
        self.tabele = QtWidgets.QTableWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabele.sizePolicy().hasHeightForWidth())
        self.tabele.setSizePolicy(sizePolicy)
        self.tabele.setObjectName("tabele")
        self.tabele.setColumnCount(6)
        self.tabele.setRowCount(4)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tabele.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tabele.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tabele.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tabele.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tabele.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tabele.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tabele.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tabele.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tabele.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tabele.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabele.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabele.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabele.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabele.setItem(3, 0, item)
        self.chart1.addWidget(self.tabele)
        self.gridLayout_3.addLayout(self.chart1, 0, 0, 1, 1)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.checkBox_RMS = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_RMS.setObjectName("checkBox_RMS")
        self.verticalLayout_6.addWidget(self.checkBox_RMS)
        self.checkBox_PRIORYTET = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_PRIORYTET.setObjectName("checkBox_PRIORYTET")
        self.verticalLayout_6.addWidget(self.checkBox_PRIORYTET)
        self.checkBox_EDF = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_EDF.setObjectName("checkBox_EDF")
        self.verticalLayout_6.addWidget(self.checkBox_EDF)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_6.addWidget(self.pushButton)
        self.gridLayout_3.addLayout(self.verticalLayout_6, 1, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_3, 1, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 687, 31))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        item = self.tabele.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tabele.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.tabele.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "3"))
        item = self.tabele.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "4"))
        item = self.tabele.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Czas nadejscia"))
        item = self.tabele.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Czas zakonczenia"))
        item = self.tabele.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Czas przetwarzania"))
        item = self.tabele.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Okres"))
        item = self.tabele.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Termin"))
        item = self.tabele.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Priorytet"))
        __sortingEnabled = self.tabele.isSortingEnabled()
        self.tabele.setSortingEnabled(False)
        self.tabele.setSortingEnabled(__sortingEnabled)
        self.checkBox_RMS.setText(_translate("MainWindow", "RMS"))
        self.checkBox_PRIORYTET.setText(_translate("MainWindow", "Priorytet"))
        self.checkBox_EDF.setText(_translate("MainWindow", "EDF"))
        self.pushButton.setText(_translate("MainWindow", "Koniec"))

